### ISSUE TITLE
Can't upload when cloudlog is installed in a virtual directory

### ISSUE THREAD

**Issue by mattmelling** [illdefined/cloudlog-adifwatch#1]
I have cloudlog installed in a virtual directory, e.g. at `http://localhost/cloudlog`. When I run `cloudlog-adifwatch http://localhost/cloudlog/ key wsjtx_log.adi`, the result is:

    <6>Performing initial full log upload.
    <2>Failed to upload log records: http://localhost/api/qso: status code 405

I've patched locally by hard coding my path but don't know enough rust to submit a decent PR.

Thanks!

**Comment by illdefined** [comment]
Thanks for the issue report. 9563e7988075e7ebcf028971c0f8070b4ad70c55 should fix this problem.
