### ISSUE TITLE
QSO API has changed in Cloudlog 2.0

### ISSUE THREAD

**Issue by garrettben** [illdefined/cloudlog-adifwatch#3]
The New API requires a station_profile_id field as described in https://github.com/magicbug/Cloudlog/wiki/API.  ADIF upload to Cloudlog 2.0 now results in a 500 error because of the missing field.

**Comment by illdefined** [comment]
I’ll take care of it tomorrow.

**Comment by illdefined** [comment]
Feel free to check out <https://github.com/illdefined/cloudlog-adifwatch/commit/610f8e8b3dc03bb45fabc2cc317873e7e77a148e>.

I am still considering if it is possible to safely determine the station profile ID automatically.

**Comment by illdefined** [comment]
There is also a pre‐release on [crates.io](https://crates.io/crates/cloudlog-adifwatch/0.0.16-alpha) and a [Windows build](https://github.com/illdefined/cloudlog-adifwatch/releases/tag/0.0.16-alpha).

**Comment by garrettben** [comment]
Built with `./.cargo/bin/cargo +nightly install cloudlog-adifwatch --git https://github.com/illdefined/cloudlog-adifwatch --rev 610f8e8b3dc03bb45fabc2cc317873e7e77a148e` and verified working with station ID

Thanks for fixing so quickly.

**Comment by illdefined** [comment]
Fixed in 0.0.16:

- https://github.com/illdefined/cloudlog-adifwatch/releases/tag/0.0.16
- https://crates.io/crates/cloudlog-adifwatch/0.0.16
